# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/

modLoader = "lowcodefml"
loaderVersion = "[1,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

license = "AGPL-3.0"
issueTrackerURL = "https://github.com/Mango-Minecraft-Project/SimplyCreateModel-IssueTracker/issues"
showAsResourcePack = true

[[mods]]
modId = "simply_create_model"
version = "1.0.1"
displayName = "Simply Create Model｜简单动力"
description = """Optimise many Create mod models.
简化了大部分机械动力的模型。"""
logoFile = "pack.png"
updateJSONURL = "https://api.modrinth.com/updates/yqmcXBDx/forge_updates.json"
credits = "Created By YaTangDragon, and packaged by MangoJellyPudding"
authors = "YaTangDragon, MangoJellyPudding"
displayURL = "https://modrinth.com/project/yqmcXBDx"

[[dependencies.simply_create_model]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1],[1.21.1]" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
side = "CLIENT" # BOTH, CLIENT, SERVER. default is BOTH

[[dependencies.simply_create_model]]
modId = "create"
mandatory = true
versionRange = "[0.5,)"
side = "CLIENT"